name: Detekt

on:
  pull_request:
    branches: [ master, stable-* ]
  push:
    branches: [ master, stable-* ]

jobs:
    detekt:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2
          - name: Set up JDK 11
            uses: actions/setup-java@v3
            with:
              distribution: "temurin"
              java-version: 11
          - name: Run detekt
            run: ./gradlew detekt
          - uses: actions/upload-artifact@v2
            if: ${{ always() }}
            with:
              name: detekt-report
              path: build/reports/detekt/detekt.html
