name: Lint

on:
  pull_request:
    branches: [ master, stable-* ]
  push:
    branches: [ master, stable-* ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 11
      - name: Run lint
        run: ./gradlew lint
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: lint-report
          path: build/reports/lint/lint.html

